
use EDUCA2;
go

DECLARE @IDCURSO INT;
SET @IDCURSO = 1;
SELECT * FROM CURSO WHERE cur_id = @IDCURSO;
SELECT * FROM MATRICULA WHERE cur_id = @IDCURSO;
GO

DECLARE @IDCURSO INT, @IDALUMNO INT;
SET @IDCURSO = 1;
SET @IDALUMNO = 4;
SELECT * FROM CURSO WHERE cur_id = @IDCURSO;
SELECT * FROM MATRICULA WHERE cur_id = @IDCURSO AND alu_id = @IDALUMNO;
SELECT * FROM PAGO WHERE cur_id = @IDCURSO AND alu_id = @IDALUMNO;
GO
